# Getting started with your project

In order to build a reproducible pipeline, we will be working together on a project.
The project itself will be quite simple and will simply consist is getting some data
"trapped" inside a Microsoft Excel Workbook into a data frame, and then creating
a plot. What will be important for our project is that it satisfies the following
requirements:

- Document;
- Tested;
- Reproducible.

We will start our project like someone with time constraints does, and
see how we can reach our goal of having a nice reproducible project as painlessly as
possible. There is only one catch; to make the whole process as easy as possible, we
will start our analysis by writing a Quarto file, not a standard R script.

*What Sébastien said on the matter:* 

*There seems to be two way of presenting such a workflow:

What does the complete project looks like at the end and what tools do I need?
How do I start working on it?*

*This questions should get answered in the intro?*

*Refer to [https://github.com/b-rodrigues/rap4all/issues/1#issuecomment-1327627267](https://github.com/b-rodrigues/rap4all/issues/1#issuecomment-1327627267)*

## Literate programming

### Why bother?

*Allows you to explain what you're doing as you're coding. This file can later be inflated, if
necessary, to make a package using `{fusen}`.*

## Quarto basics

*Teach some Quarto basics*

## Parametrized reports

## Project start

hpi: https://ec.europa.eu/eurostat/databrowser/bookmark/e2758aae-6a88-4684-9f6d-d0946cae3f6b?lang=fr

deflated hpi: https://ec.europa.eu/eurostat/databrowser/view/tipsho10/default/table?lang=en

prix des logements en euros courants: https://data.public.lu/fr/datasets/r/1d20f982-57e1-4ae2-a278-dc78c88c21dc

## Your project is done (?)

*So here the project is done, but actually it's just an Qmd file that gets compiled, so we would need
to explain why this is not enough, and motivate the readers to go the full way: developing packages,
using targets, and so on*